spring:
  output:
    ansi:
      enabled: always
  ##### Database #####
  datasource:
    url: jdbc:postgresql://localhost:5432/SpringBoot
    password: vuthin
    username: postgres
  ##### jpa #####
  jpa:
    hibernate:
      ddl-auto: update
  ###### send email #####
  mail:
    host: smtp.gmail.com
    username: thiravuthin@gmail.com
    password: tezpjxwbkjacggbz
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: 880843d95193a2973a14
#            client-secret: 47317dbf28a9daf96878123158edeab9affd5868
logging:
  level:
    org.springframework.security: trace

password:
  encryption:
    key: mysecretkey