spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SpringBoot
    password: vuthin
    username: postgres

  mail:
    host: smtp.gmail.com
    username: thiravuthin@gmail.com
    password: tezpjxwbkjacggbz
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  jpa:
    hibernate:
      ddl-auto: update

password:
  encryption:
    key: mytestkeyasdddds